[package]
name = "socketcan"
version = "1.1.1"
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
license = "MIT"
description = "Linux SocketCAN library"
documentation = "https://mbr.github.io/socketcan-rs/socketcan"
repository = "https://github.com/mbr/socketcan-rs"

[dependencies]
nix = "^0.5"
libc = "^0.2"
itertools = "^0.4"
